//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Web.Pages.MealPlans.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MealPlansOverview {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MealPlansOverview() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Web.Pages.MealPlans.Resources.MealPlansOverview", typeof(MealPlansOverview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meniu.
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }

        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        internal static string NewButton {
            get {
                return ResourceManager.GetString("NewButton", resourceCulture);
            }
        }

        internal static string BreadcrumbHome {
            get {
                return ResourceManager.GetString("BreadcrumbHome", resourceCulture);
            }
        }

        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }

        internal static string DeleteDialogMessage1 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage1", resourceCulture);
            }
        }

        internal static string DeleteDialogMessage2 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage2", resourceCulture);
            }
        }

        internal static string DialogYesButton {
            get {
                return ResourceManager.GetString("DialogYesButton", resourceCulture);
            }
        }

        internal static string DialogNoButton {
            get {
                return ResourceManager.GetString("DialogNoButton", resourceCulture);
            }
        }

        internal static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }

        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }

        internal static string DeleteSucceeded {
            get {
                return ResourceManager.GetString("DeleteSucceeded", resourceCulture);
            }
        }

        internal static string ColumnIndex {
            get {
                return ResourceManager.GetString("ColumnIndex", resourceCulture);
            }
        }

        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
    }
}
