//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Web.Pages.MealPlans.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShoppingListEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShoppingListEdit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Web.Pages.MealPlans.Resources.ShoppingListEdit", typeof(ShoppingListEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add meal plan.
        /// </summary>
        internal static string AddMealPlanButton {
            get {
                return ResourceManager.GetString("AddMealPlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe.
        /// </summary>
        internal static string AddRecipeButton {
            get {
                return ResourceManager.GetString("AddRecipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to overview.
        /// </summary>
        internal static string BackToOverviewButton {
            get {
                return ResourceManager.GetString("BackToOverviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list.
        /// </summary>
        internal static string BreadcrumbShoppingList {
            get {
                return ResourceManager.GetString("BreadcrumbShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping lists.
        /// </summary>
        internal static string BreadcrumbShoppingLists {
            get {
                return ResourceManager.GetString("BreadcrumbShoppingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the record. Once deleted can not be rolled back..
        /// </summary>
        internal static string DeleteDialogMessage1 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string DeleteDialogMessage2 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed..
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. Please try again..
        /// </summary>
        internal static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted successfully.
        /// </summary>
        internal static string DeleteSucceeded {
            get {
                return ResourceManager.GetString("DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogNoButton {
            get {
                return ResourceManager.GetString("DialogNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogYesButton {
            get {
                return ResourceManager.GetString("DialogYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit configuration is invalid..
        /// </summary>
        internal static string InvalidUnitConfiguration {
            get {
                return ResourceManager.GetString("InvalidUnitConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product: .
        /// </summary>
        internal static string LabelProduct {
            get {
                return ResourceManager.GetString("LabelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category: .
        /// </summary>
        internal static string LabelProductCategory {
            get {
                return ResourceManager.GetString("LabelProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity: .
        /// </summary>
        internal static string LabelQuantity {
            get {
                return ResourceManager.GetString("LabelQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop: .
        /// </summary>
        internal static string LabelShop {
            get {
                return ResourceManager.GetString("LabelShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list name: .
        /// </summary>
        internal static string LabelShoppingListName {
            get {
                return ResourceManager.GetString("LabelShoppingListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement: .
        /// </summary>
        internal static string LabelUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LabelUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a meal plan to add to the shopping list..
        /// </summary>
        internal static string MustSelectMealPlan {
            get {
                return ResourceManager.GetString("MustSelectMealPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a recipe to add to the shopping list..
        /// </summary>
        internal static string MustSelectRecipe {
            get {
                return ResourceManager.GetString("MustSelectRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a shop first..
        /// </summary>
        internal static string MustSelectShopFirst {
            get {
                return ResourceManager.GetString("MustSelectShopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed. Please try again..
        /// </summary>
        internal static string SaveFailedMessage {
            get {
                return ResourceManager.GetString("SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved successfully.
        /// </summary>
        internal static string SaveSucceeded {
            get {
                return ResourceManager.GetString("SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products:.
        /// </summary>
        internal static string TableCaptionProducts {
            get {
                return ResourceManager.GetString("TableCaptionProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a meal plan.
        /// </summary>
        internal static string SelectMealPlanModalTitle {
            get {
                return ResourceManager.GetString("SelectMealPlanModalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a recipe.
        /// </summary>
        internal static string SelectRecipeModalTitle {
            get {
                return ResourceManager.GetString("SelectRecipeModalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter shopping list name.
        /// </summary>
        internal static string PlaceholderShoppingListName {
            get {
                return ResourceManager.GetString("PlaceholderShoppingListName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity for the product.
        /// </summary>
        internal static string PlaceholderQuantity {
            get {
                return ResourceManager.GetString("PlaceholderQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The quantity for the product must be a positive number.
        /// </summary>
        public static string QuantityPositiveNumber {
            get {
                return ResourceManager.GetString("QuantityPositiveNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the ingredient.
        /// </summary>
        public static string SelectUnitOfMeasurement {
            get {
                return ResourceManager.GetString("SelectUnitOfMeasurement", resourceCulture);
            }
        }
    }
}
