//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Web.Pages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivacyPolicy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Web.Pages.Resources.PrivacyPolicy", typeof(PrivacyPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may update this policy from time to time. Continued use of the app after changes are published constitutes acceptance of the updated policy..
        /// </summary>
        internal static string ChangesBody {
            get {
                return ResourceManager.GetString("ChangesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this policy.
        /// </summary>
        internal static string ChangesHeading {
            get {
                return ResourceManager.GetString("ChangesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealPlanner is not directed to children under 13, and we do not knowingly collect personal information from children..
        /// </summary>
        internal static string ChildrenBody {
            get {
                return ResourceManager.GetString("ChildrenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s privacy.
        /// </summary>
        internal static string ChildrenHeading {
            get {
                return ResourceManager.GetString("ChildrenHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions about this privacy policy, please reach out via the Contact Us page in the app..
        /// </summary>
        internal static string ContactBody {
            get {
                return ResourceManager.GetString("ContactBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactHeading {
            get {
                return ResourceManager.GetString("ContactHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you create an account we collect your email address, username, and password (stored securely as a hash, never in plain text). We also store the recipes, products, meal plans, shopping lists, and shops you create while using the app..
        /// </summary>
        internal static string DataCollectedBody {
            get {
                return ResourceManager.GetString("DataCollectedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information we collect.
        /// </summary>
        internal static string DataCollectedHeading {
            get {
                return ResourceManager.GetString("DataCollectedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We retain your data for as long as your account remains active. You may request deletion of your account and associated data at any time..
        /// </summary>
        internal static string DataRetentionBody {
            get {
                return ResourceManager.GetString("DataRetentionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retention.
        /// </summary>
        internal static string DataRetentionHeading {
            get {
                return ResourceManager.GetString("DataRetentionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is stored in a secured database and is only accessible through your authenticated account..
        /// </summary>
        internal static string DataStorageBody {
            get {
                return ResourceManager.GetString("DataStorageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data storage and security.
        /// </summary>
        internal static string DataStorageHeading {
            get {
                return ResourceManager.GetString("DataStorageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use this information solely to provide the meal planning, recipe, and shopping list features of the app. We do not sell or share your personal data with third parties for marketing purposes..
        /// </summary>
        internal static string DataUseBody {
            get {
                return ResourceManager.GetString("DataUseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we use your information.
        /// </summary>
        internal static string DataUseHeading {
            get {
                return ResourceManager.GetString("DataUseHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealPlanner (&quot;the app&quot;) respects your privacy. This policy explains what information we collect, how we use it, and the choices you have..
        /// </summary>
        internal static string IntroBody {
            get {
                return ResourceManager.GetString("IntroBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string IntroHeading {
            get {
                return ResourceManager.GetString("IntroHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: 30 July 2026.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access, update, or delete your personal data at any time from within the app, or by contacting us using the Contact Us page..
        /// </summary>
        internal static string YourRightsBody {
            get {
                return ResourceManager.GetString("YourRightsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rights.
        /// </summary>
        internal static string YourRightsHeading {
            get {
                return ResourceManager.GetString("YourRightsHeading", resourceCulture);
            }
        }
    }
}
