//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeBook.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecipeBookSharedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecipeBookSharedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeBook.Shared.Resources.RecipeBookSharedMessages", typeof(RecipeBookSharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the display sequence for the category..
        /// </summary>
        public static string CategoryDisplaySequenceRequired {
            get {
                return ResourceManager.GetString("CategoryDisplaySequenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image for the recipe..
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image provided is too large..
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The quantity for the ingredient must be a positive number..
        /// </summary>
        public static string IngredientQuantityPositive {
            get {
                return ResourceManager.GetString("IngredientQuantityPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the ingredient..
        /// </summary>
        public static string IngredientUnitRequired {
            get {
                return ResourceManager.GetString("IngredientUnitRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The product category requires a name..
        /// </summary>
        public static string ProductCategoryNameRequired {
            get {
                return ResourceManager.GetString("ProductCategoryNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a category for the product..
        /// </summary>
        public static string ProductCategoryRequired {
            get {
                return ResourceManager.GetString("ProductCategoryRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select an image for the product..
        /// </summary>
        public static string ProductImageRequired {
            get {
                return ResourceManager.GetString("ProductImageRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The product requires a name..
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the product..
        /// </summary>
        public static string ProductUnitRequired {
            get {
                return ResourceManager.GetString("ProductUnitRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The recipe category requires a name..
        /// </summary>
        public static string RecipeCategoryNameRequired {
            get {
                return ResourceManager.GetString("RecipeCategoryNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a category for the recipe..
        /// </summary>
        public static string RecipeCategoryRequired {
            get {
                return ResourceManager.GetString("RecipeCategoryRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a recipe for the ingredient..
        /// </summary>
        public static string RecipeIdRequired {
            get {
                return ResourceManager.GetString("RecipeIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The recipe requires a name..
        /// </summary>
        public static string RecipeNameRequired {
            get {
                return ResourceManager.GetString("RecipeNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The recipe requires at least one ingredient..
        /// </summary>
        public static string RecipeRequiresIngredients {
            get {
                return ResourceManager.GetString("RecipeRequiresIngredients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The unit requires a name..
        /// </summary>
        public static string UnitNameRequired {
            get {
                return ResourceManager.GetString("UnitNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnitType must be between 0 and 3..
        /// </summary>
        public static string UnitTypeRange {
            get {
                return ResourceManager.GetString("UnitTypeRange", resourceCulture);
            }
        }
    }
}
