//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Web.Pages.RecipeBooks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecipeEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecipeEdit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Web.Pages.RecipeBooks.Resources.RecipeEdit", typeof(RecipeEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to overview.
        /// </summary>
        internal static string BackToOverviewButton {
            get {
                return ResourceManager.GetString("BackToOverviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string BreadcrumbRecipe {
            get {
                return ResourceManager.GetString("BreadcrumbRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string BreadcrumbRecipes {
            get {
                return ResourceManager.GetString("BreadcrumbRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the record. Once deleted can not be rolled back..
        /// </summary>
        internal static string DeleteDialogMessage1 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string DeleteDialogMessage2 {
            get {
                return ResourceManager.GetString("DeleteDialogMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed..
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. Please try again..
        /// </summary>
        internal static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted successfully.
        /// </summary>
        internal static string DeleteSucceeded {
            get {
                return ResourceManager.GetString("DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogNoButton {
            get {
                return ResourceManager.GetString("DialogNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogYesButton {
            get {
                return ResourceManager.GetString("DialogYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same ingredient was added to the recipe with a different unit of measurement..
        /// </summary>
        internal static string DuplicateIngredientError {
            get {
                return ResourceManager.GetString("DuplicateIngredientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the limit. Maximum allowed size is &lt;strong&gt;{0} MB&lt;/strong&gt;..
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient: .
        /// </summary>
        internal static string LabelIngredient {
            get {
                return ResourceManager.GetString("LabelIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient category: .
        /// </summary>
        internal static string LabelIngredientCategory {
            get {
                return ResourceManager.GetString("LabelIngredientCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original source: .
        /// </summary>
        internal static string LabelOriginalSource {
            get {
                return ResourceManager.GetString("LabelOriginalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity: .
        /// </summary>
        internal static string LabelQuantity {
            get {
                return ResourceManager.GetString("LabelQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe category: .
        /// </summary>
        internal static string LabelRecipeCategory {
            get {
                return ResourceManager.GetString("LabelRecipeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name: .
        /// </summary>
        internal static string LabelRecipeName {
            get {
                return ResourceManager.GetString("LabelRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image: .
        /// </summary>
        internal static string LabelSelectImage {
            get {
                return ResourceManager.GetString("LabelSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement: .
        /// </summary>
        internal static string LabelUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LabelUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ingredients:.
        /// </summary>
        internal static string ListOfIngredients {
            get {
                return ResourceManager.GetString("ListOfIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed. Please try again..
        /// </summary>
        internal static string SaveFailedMessage {
            get {
                return ResourceManager.GetString("SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved successfully.
        /// </summary>
        internal static string SaveSucceeded {
            get {
                return ResourceManager.GetString("SaveSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter recipe name.
        /// </summary>
        internal static string PlaceholderRecipeName {
            get {
                return ResourceManager.GetString("PlaceholderRecipeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the url for the original source.
        /// </summary>
        internal static string PlaceholderOriginalSource {
            get {
                return ResourceManager.GetString("PlaceholderOriginalSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity for the product.
        /// </summary>
        internal static string PlaceholderQuantity {
            get {
                return ResourceManager.GetString("PlaceholderQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The quantity for the ingredient must be a positive number.
        /// </summary>
        public static string QuantityPositiveNumber {
            get {
                return ResourceManager.GetString("QuantityPositiveNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the ingredient.
        /// </summary>
        public static string SelectUnitOfMeasurement {
            get {
                return ResourceManager.GetString("SelectUnitOfMeasurement", resourceCulture);
            }
        }
    }
}
