//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MealPlannerSharedMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MealPlannerSharedMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.Shared.Resources.MealPlannerSharedMessages", typeof(MealPlannerSharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The display index for the product category must be a positive number..
        /// </summary>
        public static string DisplayIndexPositive {
            get {
                return ResourceManager.GetString("DisplayIndexPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The meal plan requires at least one recipe..
        /// </summary>
        public static string MealPlanRequiresRecipes {
            get {
                return ResourceManager.GetString("MealPlanRequiresRecipes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The quantity for the product must be a positive number..
        /// </summary>
        public static string ProductQuantityPositive {
            get {
                return ResourceManager.GetString("ProductQuantityPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a shopping list for the product..
        /// </summary>
        public static string ShoppingListRequired {
            get {
                return ResourceManager.GetString("ShoppingListRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The recipe requires at least one product..
        /// </summary>
        public static string ShoppingListRequiresProducts {
            get {
                return ResourceManager.GetString("ShoppingListRequiresProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The shop requires at least product category order..
        /// </summary>
        public static string ShopRequiresCategoryOrder {
            get {
                return ResourceManager.GetString("ShopRequiresCategoryOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the product..
        /// </summary>
        public static string UnitRequired {
            get {
                return ResourceManager.GetString("UnitRequired", resourceCulture);
            }
        }
    }
}
