//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MealPlannerSharedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MealPlannerSharedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.Shared.Resources.MealPlannerSharedMessages", typeof(MealPlannerSharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display index for the product category must be a positive number..
        /// </summary>
        public static string DisplayIndexPositive {
            get {
                return ResourceManager.GetString("DisplayIndexPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the email exists, a reset link has been sent..
        /// </summary>
        public static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meal plan requires a name..
        /// </summary>
        public static string MealPlanNameRequired {
            get {
                return ResourceManager.GetString("MealPlanNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The meal plan requires at least one recipe..
        /// </summary>
        public static string MealPlanRequiresRecipes {
            get {
                return ResourceManager.GetString("MealPlanRequiresRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords do not match..
        /// </summary>
        public static string NewPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meal plans found..
        /// </summary>
        public static string NoMealPlansFound {
            get {
                return ResourceManager.GetString("NoMealPlansFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipes found..
        /// </summary>
        public static string NoRecipesFound {
            get {
                return ResourceManager.GetString("NoRecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shops available..
        /// </summary>
        public static string NoShopsAvailable {
            get {
                return ResourceManager.GetString("NoShopsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully. Please log in..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity for the product must be a positive number..
        /// </summary>
        public static string ProductQuantityPositive {
            get {
                return ResourceManager.GetString("ProductQuantityPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated..
        /// </summary>
        public static string ProfileUpdatedSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please log in..
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a shop first..
        /// </summary>
        public static string SelectShopFirst {
            get {
                return ResourceManager.GetString("SelectShopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shop requires a name..
        /// </summary>
        public static string ShopNameRequired {
            get {
                return ResourceManager.GetString("ShopNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate shopping list..
        /// </summary>
        public static string ShoppingListGenerateFailed {
            get {
                return ResourceManager.GetString("ShoppingListGenerateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The shopping list requires a name..
        /// </summary>
        public static string ShoppingListNameRequired {
            get {
                return ResourceManager.GetString("ShoppingListNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a shopping list for the product..
        /// </summary>
        public static string ShoppingListRequired {
            get {
                return ResourceManager.GetString("ShoppingListRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe requires at least one product..
        /// </summary>
        public static string ShoppingListRequiresProducts {
            get {
                return ResourceManager.GetString("ShoppingListRequiresProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shop requires at least product category order..
        /// </summary>
        public static string ShopRequiresCategoryOrder {
            get {
                return ResourceManager.GetString("ShopRequiresCategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a unit of measurement for the product..
        /// </summary>
        public static string UnitRequired {
            get {
                return ResourceManager.GetString("UnitRequired", resourceCulture);
            }
        }
    }
}
