//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Web.Pages.Identities.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Register {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Web.Pages.Identities.Resources.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string PageTitle {
            get { return ResourceManager.GetString("PageTitle", resourceCulture); }
        }

        internal static string UsernameLabel {
            get { return ResourceManager.GetString("UsernameLabel", resourceCulture); }
        }

        internal static string FirstNameLabel {
            get { return ResourceManager.GetString("FirstNameLabel", resourceCulture); }
        }

        internal static string LastNameLabel {
            get { return ResourceManager.GetString("LastNameLabel", resourceCulture); }
        }

        internal static string PhoneNumberLabel {
            get { return ResourceManager.GetString("PhoneNumberLabel", resourceCulture); }
        }

        internal static string EmailLabel {
            get { return ResourceManager.GetString("EmailLabel", resourceCulture); }
        }

        internal static string PasswordLabel {
            get { return ResourceManager.GetString("PasswordLabel", resourceCulture); }
        }

        internal static string ConfirmPasswordLabel {
            get { return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture); }
        }

        internal static string RegisterButton {
            get { return ResourceManager.GetString("RegisterButton", resourceCulture); }
        }

        internal static string BackToLoginLink {
            get { return ResourceManager.GetString("BackToLoginLink", resourceCulture); }
        }

        internal static string RegisterFailed {
            get { return ResourceManager.GetString("RegisterFailed", resourceCulture); }
        }

        internal static string RegisterSucceeded {
            get { return ResourceManager.GetString("RegisterSucceeded", resourceCulture); }
        }

        internal static string PlaceholderUsername {
            get { return ResourceManager.GetString("PlaceholderUsername", resourceCulture); }
        }

        internal static string PlaceholderFirstName {
            get { return ResourceManager.GetString("PlaceholderFirstName", resourceCulture); }
        }

        internal static string PlaceholderLastName {
            get { return ResourceManager.GetString("PlaceholderLastName", resourceCulture); }
        }

        internal static string PlaceholderPhoneNumber {
            get { return ResourceManager.GetString("PlaceholderPhoneNumber", resourceCulture); }
        }

        internal static string PlaceholderEmail {
            get { return ResourceManager.GetString("PlaceholderEmail", resourceCulture); }
        }

        internal static string PlaceholderPassword {
            get { return ResourceManager.GetString("PlaceholderPassword", resourceCulture); }
        }

        internal static string PlaceholderConfirmPassword {
            get { return ResourceManager.GetString("PlaceholderConfirmPassword", resourceCulture); }
        }
    }
}
