//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Mobile.Pages.RecipeBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecipeEditPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecipeEditPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Mobile.Pages.RecipeBook.Resources.RecipeEditPage", typeof(RecipeEditPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        internal static string AddIngredientLabel {
            get {
                return ResourceManager.GetString("AddIngredientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All categories.
        /// </summary>
        internal static string AllCategoriesOption {
            get {
                return ResourceManager.GetString("AllCategoriesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe category.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found.
        /// </summary>
        internal static string EmptyCategoriesLabel {
            get {
                return ResourceManager.GetString("EmptyCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ingredients yet..
        /// </summary>
        internal static string EmptyIngredients {
            get {
                return ResourceManager.GetString("EmptyIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found.
        /// </summary>
        internal static string EmptyProductCategoriesLabel {
            get {
                return ResourceManager.GetString("EmptyProductCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found.
        /// </summary>
        internal static string EmptyProductsLabel {
            get {
                return ResourceManager.GetString("EmptyProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No units found.
        /// </summary>
        internal static string EmptyUnitsLabel {
            get {
                return ResourceManager.GetString("EmptyUnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string IngredientsLabel {
            get {
                return ResourceManager.GetString("IngredientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick image.
        /// </summary>
        internal static string PickImageButton {
            get {
                return ResourceManager.GetString("PickImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter recipe name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity.
        /// </summary>
        internal static string PlaceholderQuantity {
            get {
                return ResourceManager.GetString("PlaceholderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search by name....
        /// </summary>
        internal static string PlaceholderSearchCategories {
            get {
                return ResourceManager.GetString("PlaceholderSearchCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search by name....
        /// </summary>
        internal static string PlaceholderSearchProductCategories {
            get {
                return ResourceManager.GetString("PlaceholderSearchProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search by name....
        /// </summary>
        internal static string PlaceholderSearchProducts {
            get {
                return ResourceManager.GetString("PlaceholderSearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search by name....
        /// </summary>
        internal static string PlaceholderSearchUnits {
            get {
                return ResourceManager.GetString("PlaceholderSearchUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the url for the original source.
        /// </summary>
        internal static string PlaceholderSource {
            get {
                return ResourceManager.GetString("PlaceholderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient category.
        /// </summary>
        internal static string ProductCategoryTitle {
            get {
                return ResourceManager.GetString("ProductCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string SelectProductTitle {
            get {
                return ResourceManager.GetString("SelectProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original source.
        /// </summary>
        internal static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement.
        /// </summary>
        internal static string UnitTitle {
            get {
                return ResourceManager.GetString("UnitTitle", resourceCulture);
            }
        }
    }
}
