//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Services.Converters.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConverterMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConverterMessages() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Services.Converters.Resources.ConverterMessages", typeof(ConverterMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string IngredientProductBaseUnitMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientProductBaseUnitMustNotBeNull", resourceCulture);
            }
        }

        public static string IngredientProductMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientProductMustNotBeNull", resourceCulture);
            }
        }

        public static string IngredientUnitMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientUnitMustNotBeNull", resourceCulture);
            }
        }

        public static string LiquidConversionFromNotSupported {
            get {
                return ResourceManager.GetString("LiquidConversionFromNotSupported", resourceCulture);
            }
        }

        public static string LiquidConversionToNotSupported {
            get {
                return ResourceManager.GetString("LiquidConversionToNotSupported", resourceCulture);
            }
        }

        public static string MassConversionFromNotSupported {
            get {
                return ResourceManager.GetString("MassConversionFromNotSupported", resourceCulture);
            }
        }

        public static string MassConversionToNotSupported {
            get {
                return ResourceManager.GetString("MassConversionToNotSupported", resourceCulture);
            }
        }

        public static string ProductBaseUnitMustBeSet {
            get {
                return ResourceManager.GetString("ProductBaseUnitMustBeSet", resourceCulture);
            }
        }

        public static string ProductMustBeSet {
            get {
                return ResourceManager.GetString("ProductMustBeSet", resourceCulture);
            }
        }

        public static string ShoppingListNameFormat {
            get {
                return ResourceManager.GetString("ShoppingListNameFormat", resourceCulture);
            }
        }

        public static string UnitMustBeSet {
            get {
                return ResourceManager.GetString("UnitMustBeSet", resourceCulture);
            }
        }

        public static string UnitTypeMismatch {
            get {
                return ResourceManager.GetString("UnitTypeMismatch", resourceCulture);
            }
        }

        public static string UnitTypeNotSupported {
            get {
                return ResourceManager.GetString("UnitTypeNotSupported", resourceCulture);
            }
        }

        public static string VolumeConversionFromNotSupported {
            get {
                return ResourceManager.GetString("VolumeConversionFromNotSupported", resourceCulture);
            }
        }

        public static string VolumeConversionToNotSupported {
            get {
                return ResourceManager.GetString("VolumeConversionToNotSupported", resourceCulture);
            }
        }
    }
}
