//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Services.Converters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConverterMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConverterMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Services.Converters.Resources.ConverterMessages", typeof(ConverterMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.Product.BaseUnit must not be null..
        /// </summary>
        public static string IngredientProductBaseUnitMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientProductBaseUnitMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.Product must not be null..
        /// </summary>
        public static string IngredientProductMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientProductMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.Unit must not be null..
        /// </summary>
        public static string IngredientUnitMustNotBeNull {
            get {
                return ResourceManager.GetString("IngredientUnitMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from liquid unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string LiquidConversionFromNotSupported {
            get {
                return ResourceManager.GetString("LiquidConversionFromNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to liquid unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string LiquidConversionToNotSupported {
            get {
                return ResourceManager.GetString("LiquidConversionToNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from mass unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string MassConversionFromNotSupported {
            get {
                return ResourceManager.GetString("MassConversionFromNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to mass unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string MassConversionToNotSupported {
            get {
                return ResourceManager.GetString("MassConversionToNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.BaseUnit must be set before converting to ShoppingListProduct..
        /// </summary>
        public static string ProductBaseUnitMustBeSet {
            get {
                return ResourceManager.GetString("ProductBaseUnitMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product must be set before converting to ShoppingListProduct..
        /// </summary>
        public static string ProductMustBeSet {
            get {
                return ResourceManager.GetString("ProductMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list details for {0} in shop {1}.
        /// </summary>
        public static string ShoppingListNameFormat {
            get {
                return ResourceManager.GetString("ShoppingListNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit must be set before converting to ShoppingListProduct..
        /// </summary>
        public static string UnitMustBeSet {
            get {
                return ResourceManager.GetString("UnitMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from unit type {0} to {1}..
        /// </summary>
        public static string UnitTypeMismatch {
            get {
                return ResourceManager.GetString("UnitTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string UnitTypeNotSupported {
            get {
                return ResourceManager.GetString("UnitTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from volume unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string VolumeConversionFromNotSupported {
            get {
                return ResourceManager.GetString("VolumeConversionFromNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to volume unit &apos;{0}&apos; is not supported..
        /// </summary>
        public static string VolumeConversionToNotSupported {
            get {
                return ResourceManager.GetString("VolumeConversionToNotSupported", resourceCulture);
            }
        }
    }
}
