//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Mobile.Pages.MealPlans.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShoppingListEditPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShoppingListEditPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Mobile.Pages.MealPlans.Resources.ShoppingListEditPage", typeof(ShoppingListEditPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string AddProductLabel {
            get {
                return ResourceManager.GetString("AddProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products yet..
        /// </summary>
        internal static string EmptyProducts {
            get {
                return ResourceManager.GetString("EmptyProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No products found.
        /// </summary>
        internal static string EmptyProductsSearchLabel {
            get {
                return ResourceManager.GetString("EmptyProductsSearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        internal static string PlaceholderSearchProducts {
            get {
                return ResourceManager.GetString("PlaceholderSearchProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From Meal Plan.
        /// </summary>
        internal static string FromMealPlanButton {
            get {
                return ResourceManager.GetString("FromMealPlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Recipe.
        /// </summary>
        internal static string FromRecipeButton {
            get {
                return ResourceManager.GetString("FromRecipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select meal plan.
        /// </summary>
        internal static string SelectMealPlanTitle {
            get {
                return ResourceManager.GetString("SelectMealPlanTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        internal static string PlaceholderSearchMealPlans {
            get {
                return ResourceManager.GetString("PlaceholderSearchMealPlans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No meal plans found.
        /// </summary>
        internal static string EmptyMealPlansLabel {
            get {
                return ResourceManager.GetString("EmptyMealPlansLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select recipe.
        /// </summary>
        internal static string SelectRecipeTitle {
            get {
                return ResourceManager.GetString("SelectRecipeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        internal static string PlaceholderSearchRecipes {
            get {
                return ResourceManager.GetString("PlaceholderSearchRecipes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No recipes found.
        /// </summary>
        internal static string EmptyRecipesLabel {
            get {
                return ResourceManager.GetString("EmptyRecipesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shopping list name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string PlaceholderQuantity {
            get {
                return ResourceManager.GetString("PlaceholderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        internal static string ProductCategoryTitle {
            get {
                return ResourceManager.GetString("ProductCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string ProductsLabel {
            get {
                return ResourceManager.GetString("ProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select product.
        /// </summary>
        internal static string SelectProductTitle {
            get {
                return ResourceManager.GetString("SelectProductTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select shop.
        /// </summary>
        internal static string SelectShopTitle {
            get {
                return ResourceManager.GetString("SelectShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string ShopLabel {
            get {
                return ResourceManager.GetString("ShopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UnitTitle {
            get {
                return ResourceManager.GetString("UnitTitle", resourceCulture);
            }
        }
    }
}
