//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI.Mobile.Pages.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserProfilePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfilePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Mobile.Pages.Identity.Resources.UserProfilePage", typeof(UserProfilePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string LockedOutLabel {
            get {
                return ResourceManager.GetString("LockedOutLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Picture.
        /// </summary>
        internal static string PickPictureButton {
            get {
                return ResourceManager.GetString("PickPictureButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutButton {
            get {
                return ResourceManager.GetString("SignOutButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock User.
        /// </summary>
        internal static string UnlockButton {
            get {
                return ResourceManager.GetString("UnlockButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User has been unlocked successfully.
        /// </summary>
        internal static string UnlockSucceeded {
            get {
                return ResourceManager.GetString("UnlockSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
    }
}
